# Generated by Django 4.0.3 on 2023-06-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_remove_binvo_bin_size_remove_binvo_import_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='bin_number',
        ),
        migrations.RemoveField(
            model_name='binvo',
            name='closet_name',
        ),
        migrations.AddField(
            model_name='binvo',
            name='import_href',
            field=models.URLField(max_length=300, null=True, unique=True),
        ),
    ]
